cargo-features = ["strip"]

[package]
name = "derpibooru-proxy"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
lto = true

[dependencies]
lazy_static = "*"
dotenv = "*"

rocket = "*"
reqwest = { version = "*", features = ["blocking", "socks"] }
